#
# Olier
# Frontend
# Streamlit config
#

[browser]
gatherUsageStats=false

[theme]
primaryColor="#ED6E2B"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"
